In [1]:
import numpy as np

t_array = np.array([1,2,3,4], float)

print(t_array)

print(t_array[1])

[1. 2. 3. 4.]
2.0


In [2]:
t_array.dtype

dtype('float64')

In [3]:
t_array.shape

(4,)

In [8]:
data = [[1,2,3,4], [2,3,4,5], [3,4,5,6]]

a = np.array(data)

a.shape

(3, 4)

In [5]:
a.dtype

dtype('int32')

In [6]:
a.shape

(3, 4)

In [9]:
data = [[[1,2,3,4], [2,3,4,5], [3,4,5,6]], [[112,2,3,4],[2,3,4,5],[3,4,5,6]]]

b = np.array(data)

b.shape

(2, 3, 4)

In [13]:
data_a = np.array([[1,2,3,4],[2,3,4,5]])
print(data_a)

data_b = np.array(data).reshape(8,)
print(data_b)

[[1 2 3 4]
 [2 3 4 5]]
[1 2 3 4 2 3 4 5]


In [14]:
data_a = np.array([[1,2,3,4],[2,3,4,5]])
print(data_a)

data_b = np.array(data_a).flatten()
print(data_b)

[[1 2 3 4]
 [2 3 4 5]]
[1 2 3 4 2 3 4 5]


In [17]:
data_a = np.array([[1,2,3,4],[2,3,4,5]])
print(data_a)

print(data_a[1,2])

[[1 2 3 4]
 [2 3 4 5]]
4


In [18]:
data_a = np.array([[1,2,3,4],[2,3,4,5]])
print(data_a)

print(data_a[:, 1:]) #row는 모두, column은 1이상

[[1 2 3 4]
 [2 3 4 5]]
[[2 3 4]
 [3 4 5]]


In [19]:
data_a = np.array([[1,2,3,4],[2,3,4,5]])
print(data_a)

print(data_a[::1, ::2])

[[1 2 3 4]
 [2 3 4 5]]
[[1 3]
 [2 4]]


In [23]:
a = np.arange(10)
print(a)

print(np.any(a>5))

print(np.all(a>1))

[0 1 2 3 4 5 6 7 8 9]
True
False


In [25]:
a = np.arange(10)
print(a)

np.where(a>3, 1, 0)

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [27]:
a = np.arange(10)
print(a)

a[a > 3]

[0 1 2 3 4 5 6 7 8 9]


array([4, 5, 6, 7, 8, 9])

In [29]:
a = np.array([10,20,30,40,50])
b = np.array([1,3,0,2,4,3,1])

a[b]

array([20, 40, 10, 30, 50, 40, 20])